tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 1.17
    motor:
        id: 1
        init: 1722 #2048
        min: 100
        max: 3000

pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 1.17
    motor:
        id: 2
        init: 1900 #1806 #2048
        min: 0
        max: 4094
